# coordinates of the point, which will be backprojected to the camera image from the specified frame
world_frame_id: "gps_origin"
world_point:
  x: 0.0
  y: 0.0
  z: 0.0

s_P0_position: 0.01
s_P0_velocity: 0.0001

# for plkft and dkft circle (scenario 1)
#s_Q_acc: 0.001
#s_R: 0.00001
#bearing_var: 0.00001
#dkf_var: 0.05

# for dkf and dkft for helix
#s_Q_acc: 1
#s_R: 0.05
#bearing_var: 0.01
#dkf_var: 0.1

#plkf plkft for helix
s_Q_acc: 1
s_R: 0.05
bearing_var: 0.01
dkf_var: 0.1

# PLKF PLKFT and DKF DKFT for pure pursuit (2 3 scenarios vut only plkft!)
#s_Q_acc: 10
#s_R: 0.005
#bearing_var: 0.05
#dkf_var: 0.1

# DKFT/DKF for pure pursuit (scenario 3)
#s_Q_acc: 10
#s_R: 10
#bearing_var: 0.05
#dkf_var: 0.5

rate:
  # how often to publish my topic?
  publish: 10 # [Hz]
  # how often check whether msgs are arriving?
  check_subscribers: 1 # [Hz]
